# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\Python\GUI\mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 890)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(30, 130, 321, 571))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.push_create_tar = QtWidgets.QPushButton(self.tab_2)
        self.push_create_tar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_create_tar.setFont(font)
        self.push_create_tar.setObjectName("push_create_tar")
        self.verticalLayout.addWidget(self.push_create_tar)
        self.line_prim_cr_tar = QtWidgets.QLineEdit(self.tab_2)
        self.line_prim_cr_tar.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_prim_cr_tar.setFont(font)
        self.line_prim_cr_tar.setObjectName("line_prim_cr_tar")
        self.verticalLayout.addWidget(self.line_prim_cr_tar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_bd_mk = QtWidgets.QTableWidget(self.tab_2)
        self.table_bd_mk.setObjectName("table_bd_mk")
        self.table_bd_mk.setColumnCount(0)
        self.table_bd_mk.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_bd_mk)
        self.table_bd_tara = QtWidgets.QTableWidget(self.tab_2)
        self.table_bd_tara.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_bd_tara.setObjectName("table_bd_tara")
        self.table_bd_tara.setColumnCount(0)
        self.table_bd_tara.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_bd_tara)
        self.table_bd_rab_c = QtWidgets.QTableWidget(self.tab_2)
        self.table_bd_rab_c.setObjectName("table_bd_rab_c")
        self.table_bd_rab_c.setColumnCount(0)
        self.table_bd_rab_c.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_bd_rab_c)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_sod_mk = QtWidgets.QTableWidget(self.tab_2)
        self.table_sod_mk.setMinimumSize(QtCore.QSize(0, 444))
        self.table_sod_mk.setObjectName("table_sod_mk")
        self.table_sod_mk.setColumnCount(0)
        self.table_sod_mk.setRowCount(0)
        self.verticalLayout.addWidget(self.table_sod_mk)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Поток"))
        self.push_create_tar.setText(_translate("MainWindow", "Создать тару"))
        self.line_prim_cr_tar.setPlaceholderText(_translate("MainWindow", "примечание..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Формирование"))
